### ISSUE TITLE
is there a way for a project manager to remove users from a project

### ISSUE THREAD

**Issue by paciorek** [ucb-rit/coldfront#183] opened 2021-05-26 21:22 UTC
I'm not seeing it, but might just be missing it.

If not available, it would probably be useful longer-term though not critical at the moment.

**Comment by kmuriki** [comment] 2021-05-28 18:42
Yeh again has to do with user account deletions and removals which are are all in the future roadmap. Please remember our goal for June 1st is to offer what we offer right now via the Google forms/spreadsheets and replace Google form/spreadsheets and not necessarily offer the best possible portal with all bells and whistles. Moving this to the post launch section. Thanks.

**Comment by matthew-li** [comment] 2021-06-07 15:16
Duplicate of #62; please refer to that issue. Closing.

**Closed by matthew-li** 2021-06-07 15:16 UTC
Labels: enhancement
